# -*- coding: utf-8 -*-
"""Heirarchy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdTkF32ToNgHAsWIXR6nCV16aS1L1C9Q
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import  PCA

df=pd.read_csv('/content/drive/MyDrive/Dataset/Iris.csv')

df.drop(['Id','Species'],axis=1,inplace=True)

scaler=StandardScaler()
x_scaled=scaler.fit_transform(df)

df.head()

pca=PCA(n_components=2)#to reduce no of columns with positive crltn
#n_components=2 -- reduce to 2 cols

pca_scaled=pca.fit_transform(x_scaled)

pca_scaled

pca_scaled.shape

plt.scatter(pca_scaled[:,0],pca_scaled[:,1])

import  scipy.cluster.hierarchy as sc
plt.figure(figsize=(10,7))
plt.title('Dendrogram')
sc.dendrogram(sc.linkage(pca_scaled,method='ward'))#method='ward' to find the distance b/w clusters
plt.show()

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score

silhouette_coefficients=[]
for k in range(2,11):
  agglo=AgglomerativeClustering(n_clusters=k, linkage='ward')
  agglo.fit(pca_scaled)
  score=silhouette_score(pca_scaled,agglo.labels_)
  silhouette_coefficients.append(score)

plt.plot(range(2,11),silhouette_coefficients)
plt.xticks(range(2,11))
plt.xlabel('Number of Clusters')
plt.ylabel('silhouette Coefficients')
plt.show()

cluster1=AgglomerativeClustering(n_clusters=2, linkage='ward')

ypred=cluster1.fit_predict(pca_scaled)
ypred

plt.scatter(pca_scaled[:,0],pca_scaled[:,1],c=ypred)